### ISSUE TITLE
Gradle Version upgrade?

### ISSUE THREAD

**Issue by nathan-sixnines** [robingenz/docker-ionic-cordova#3]
I'm getting this error after attempting to add a new cordova plugin.

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /workdir/729-android/platforms/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:27: AAPT: error: unexpected element <queries> found in <manifest>.
```

It looks like the fix is upgrading gradle to one of the versions listed here.

https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error

**Comment by nathan-sixnines** [comment]
Bit of progress, different sort of errors now.

The fix was not to upgrade gradle in the container, but just to configure the build.gradle properly.

For me that meant changing the 
```
        classpath 'com.android.tools.build:gradle:3.3.0'
```
to
```
        classpath 'com.android.tools.build:gradle:3.3.3'
```

in platforms/android/app/build.gradle

**Comment by robingenz** [comment]
So it works now?
